In [3]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr2)
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])



1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


In [4]:
zeros_arr = np.zeros((2, 3))
print("Zeros array:\n", zeros_arr)

ones_arr = np.ones((3, 2))
print("Ones array:\n", ones_arr)

full_arr = np.full((2, 2), 7)
print("Full array:\n", full_arr)

identity_arr = np.eye(4)
print("Identity matrix:\n", identity_arr)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Full array:
 [[7 7]
 [7 7]]
Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
range_arr = np.arange(0, 10, 2)  
print("arange array:", range_arr)

lin_arr = np.linspace(0, 1, 5)   
print("linspace array:", lin_arr)

rand_arr = np.random.rand(2, 3)      
randint_arr = np.random.randint(1, 100, size=(2, 3))  
print("Random float array:\n", rand_arr)
print("Random integer array:\n", randint_arr)

arange array: [0 2 4 6 8]
linspace array: [0.   0.25 0.5  0.75 1.  ]
Random float array:
 [[0.69174236 0.85419825 0.97017316]
 [0.86355654 0.05321901 0.61912007]]
Random integer array:
 [[34 83 58]
 [42 12 81]]


In [6]:
exercise1_a = np.zeros((4, 4))
exercise1_b = np.arange(10, 51, 5)
print(exercise1_a)
print(exercise1_b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[10 15 20 25 30 35 40 45 50]


In [7]:
sample = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", sample)
print("Shape:", sample.shape)      
print("Dimensions:", sample.ndim) 
print("Size:", sample.size)        
print("Data type:", sample.dtype)  

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64


In [8]:
reshaped = sample.reshape(3, 2)   
print("Reshaped (3x2):\n", reshaped)

flat = sample.flatten()
print("Flattened:", flat)

print("Transpose:\n", sample.T)

Reshaped (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Flattened: [1 2 3 4 5 6]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

joined = np.concatenate((a, b))
print("Concatenated:", joined)

stacked_v = np.vstack((a, b))   
stacked_h = np.hstack((a, b))  
print("Vertical stack:\n", stacked_v)
print("Horizontal stack:", stacked_h)

Concatenated: [1 2 3 4 5 6]
Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal stack: [1 2 3 4 5 6]


In [10]:
unsorted = np.array([5, 2, 9, 1, 7])
sorted_arr = np.sort(unsorted)
print("Original:", unsorted)
print("Sorted:", sorted_arr)

Original: [5 2 9 1 7]
Sorted: [1 2 5 7 9]


In [11]:
ex2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", ex2.shape)
print("Size:", ex2.size)
print("Reshaped:\n", ex2.reshape(3, 2))

Shape: (2, 3)
Size: 6
Reshaped:
 [[1 2]
 [3 4]
 [5 6]]


In [12]:
x = np.array([10, 20, 30, 40])
y = np.array([1, 2, 3, 4])

print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)
print("Power:", x ** 2)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Power: [ 100  400  900 1600]


In [13]:
data = np.array([4, 8, 15, 16, 23, 42])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Standard deviation:", np.std(data))
print("Variance:", np.var(data))

Sum: 108
Mean: 18.0
Minimum: 4
Maximum: 42
Standard deviation: 12.315302134607444
Variance: 151.66666666666666


In [14]:
nums = np.array([1, 4, 9, 16])

print("Square root:", np.sqrt(nums))
print("Exponential:", np.exp(nums))
print("Natural log:", np.log(nums))
print("Sine:", np.sin(nums))

Square root: [1. 2. 3. 4.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Natural log: [0.         1.38629436 2.19722458 2.77258872]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]


In [15]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("Element-wise multiplication:\n", m1 * m2)
print("Matrix multiplication (dot):\n", np.dot(m1, m2))
print("Matrix multiplication (matmul):\n", np.matmul(m1, m2))

Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication (dot):
 [[19 22]
 [43 50]]
Matrix multiplication (matmul):
 [[19 22]
 [43 50]]


In [16]:
p = np.array([2, 4, 6, 8, 10])
q = np.array([1, 3, 5, 7, 9])

ex3_sum = p + q
ex3_product = p * q
print("Sum:", ex3_sum)
print("Product:", ex3_product)
print("Mean of sum:", np.mean(ex3_sum))

Sum: [ 3  7 11 15 19]
Product: [ 2 12 30 56 90]
Mean of sum: 11.0


In [17]:
arr = np.array([10, 20, 30, 40, 50, 60])

print("Full array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Elements from index 1 to 3:", arr[1:4])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])

Full array: [10 20 30 40 50 60]
First element: 10
Last element: 60
Elements from index 1 to 3: [20 30 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]


In [18]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print("Matrix:\n", matrix)
print("Element at row 1, col 2:", matrix[1, 2])
print("First row:", matrix[0, :])
print("First column:", matrix[:, 0])
print("Sub-matrix (rows 0-1, cols 1-2):\n", matrix[0:2, 1:3])

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, col 2: 6
First row: [1 2 3]
First column: [1 4 7]
Sub-matrix (rows 0-1, cols 1-2):
 [[2 3]
 [5 6]]
